@php($registro = $presupuesto ?? null)
<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Proyecto <span class="text-red-600">*</span></label><select id="proyecto_id" name="proyecto_id" required class="w-full rounded-md border-gray-300"><option value="">Seleccione un proyecto</option>@foreach($proyectos as $proyecto)<option value="{{ $proyecto->id }}" data-aprobado="{{ $proyecto->presupuesto_aprobado }}" @selected((string)old('proyecto_id',$registro?->proyecto_id ?? request('proyecto_id'))===(string)$proyecto->id)>{{ $proyecto->codigo }} - {{ $proyecto->nombre }} | Aprobado: USD {{ number_format((float)$proyecto->presupuesto_aprobado,2) }}</option>@endforeach</select><x-input-error :messages="$errors->get('proyecto_id')" class="mt-1" /></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Año <span class="text-red-600">*</span></label><input type="number" name="anio" min="2000" max="2100" required value="{{ old('anio',$registro?->anio ?? now()->year) }}" class="w-full rounded-md border-gray-300"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Periodo <span class="text-red-600">*</span></label><select name="periodo" required class="w-full rounded-md border-gray-300">@foreach($periodos as $periodo)<option value="{{ $periodo->value }}" @selected(old('periodo',$registro?->periodo)===$periodo->value)>{{ $periodo->value }}</option>@endforeach</select></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Fecha de corte <span class="text-red-600">*</span></label><input type="date" name="fecha_corte" required value="{{ old('fecha_corte',$registro?->fecha_corte?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" class="w-full rounded-md border-gray-300"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Estado <span class="text-red-600">*</span></label><select name="estado" required class="w-full rounded-md border-gray-300">@foreach($estados as $estado)<option value="{{ $estado->value }}" @selected(old('estado',$registro?->estado ?? 'Borrador')===$estado->value)>{{ $estado->value }}</option>@endforeach</select><p class="mt-1 text-xs text-gray-500">Al cerrar el registro ya no podrá editarse.</p></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Monto programado <span class="text-red-600">*</span></label><input type="number" step="0.01" min="0.01" name="monto_programado" required value="{{ old('monto_programado',$registro?->monto_programado) }}" class="w-full rounded-md border-gray-300"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Presupuesto vigente <span class="text-red-600">*</span></label><input id="presupuesto_vigente" type="number" step="0.01" min="0" name="presupuesto_vigente" required value="{{ old('presupuesto_vigente',$registro?->presupuesto_vigente) }}" class="w-full rounded-md border-gray-300"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Monto ejecutado <span class="text-red-600">*</span></label><input type="number" step="0.01" min="0" name="monto_ejecutado" required value="{{ old('monto_ejecutado',$registro?->monto_ejecutado) }}" class="w-full rounded-md border-gray-300"></div>
    <div class="rounded-md bg-blue-50 p-4 text-sm text-blue-800"><strong>Presupuesto aprobado del proyecto:</strong><p id="aprobadoProyecto" class="mt-1 text-lg">Seleccione un proyecto</p></div>
    <div class="md:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Observaciones</label><textarea name="observaciones" rows="3" class="w-full rounded-md border-gray-300">{{ old('observaciones',$registro?->observaciones) }}</textarea></div>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const p=document.getElementById('proyecto_id'),v=document.getElementById('presupuesto_vigente'),t=document.getElementById('aprobadoProyecto');const actualizar=()=>{const o=p.options[p.selectedIndex],m=o?.dataset.aprobado;if(m){t.textContent='USD '+Number(m).toLocaleString('es-EC',{minimumFractionDigits:2});if(!v.value)v.value=Number(m).toFixed(2)}else t.textContent='Seleccione un proyecto'};p.addEventListener('change',actualizar);actualizar()});</script>
